cartpole_dt:
    env: 'CartPole-v0'
    run: DT
    stop:
      evaluation/episode_reward_mean: 200
      training_iteration: 100
    config:
        input: 'dataset'
        input_config:         
            paths: 'tests/data/cartpole/large.json'
            format: 'json'
        num_workers: 0
        actions_in_input_normalized: True
        clip_actions: False
        # training
        framework: torch
        train_batch_size: 2048
        shuffle_buffer_size: 20
        horizon: 200
        max_ep_len: 200
        target_return: 200
        lr: 0.001
        weight_decay: 0.0001
        betas: [0.9, 0.95]
        # model
        max_seq_len: 5
        num_layers: 2
        num_heads: 1
        embed_dim: 64
        # evaluation
        evaluation_config:
            explore: False
            input: sampler
        evaluation_duration: 10
        evaluation_duration_unit: episodes
        evaluation_interval: 1
        evaluation_num_workers: 0
        evaluation_parallel_to_training: False
