pendulum_crr:
    env: 'Pendulum-v1'
    run: DT
    stop:
        # We could make this -200, but given that we have 4 cpus for our tests, we will have to settle for -300.
        evaluation/episode_reward_mean: -300
        timesteps_total: 2000000
    config:
        input: 'dataset'
        input_config:         
            paths: 'tests/data/pendulum/pendulum_replay_v1.1.0.zip'
            format: 'json'
        actions_in_input_normalized: True
        clip_actions: False
        # training
        framework: torch
        train_batch_size: 2048
        target_return: 200
        lr: 0.001
        optimizer:
            weight_decay: 0.0001
            betas: [0.9, 0.95]
        replay_buffer_config:
            capacity: 20
        # model
        model:
            max_seq_len: 5
        num_layers: 2
        num_heads: 1
        embed_dim: 64
        # rollout
        horizon: 200
        # evaluation
        evaluation_config:
            explore: False
            input: sampler
        evaluation_duration: 10
        evaluation_duration_unit: episodes
        evaluation_interval: 1
        evaluation_num_workers: 1
        evaluation_parallel_to_training: True